image: node:18-alpine   # npm ပါနေပြီးသား — apk add မလုပ်ရတော့

stages:
  - cache
  - test
  - build 
  - dockerize

npm install:
  stage: cache
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: push 
    paths:
      - node_modules/
  script:
    - echo "Installing npm dependencies..."
    - npm ci


eslint:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules/
  script: 
    - echo "Running ESLint..."
    - npx eslint . --fix 
  allow_failure: true




unit-tests:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules/
  script:
    - echo "Running unit tests..."
    - npx jest --coverage
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 10 mins



ts-build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths: 
      - node_modules/
  script:
  - echo "building ts to js"
  - npm run build:ts
  artifacts:
    paths: 
      - dist/
    expire_in: 10 days


docker-build:
  stage: dockerize
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_BUILDKIT: "0"
  script:
    # ၁။ GitLab Registry သို့ Login ဝင်ခြင်း
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    
    # ၂။ Image ကို တည်ဆောက်ခြင်း (အမည်ကို $CI_REGISTRY_IMAGE သုံးပြီး ပေးပါမယ်)
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    
    # ၃။ တည်ဆောက်ပြီးသား Image ကို Registry သို့ Upload တင်ခြင်း
    - docker push $CI_REGISTRY_IMAGE:latest