image: node:18-alpine   # npm ပါနေပြီးသား — apk add မလုပ်ရတော့

stages:
  - cache
  - build
  - test

npm install:
  stage: cache
  cache:
    paths:
      - node_modules/
  script:
    - echo "Installing npm dependencies..."
    - npm install


eslint:
  stage: test
  cache:
    paths:
      - node_modules/
  when: manual
  script: 
    - echo "Running ESLint..."
    - npx eslint .


# unit-tests:
#   stage: test
#   when: manual
#   script:
#     # - npx jest --coverage  
#       - echo "Running unit tests...
just-things:
  stage: test
  script:
    - echo "Installing npm dependencies..."
    # - npm install
    - echo "Running unit tests..."
